apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: push-lab
resources:
  - grafana.yaml
configMapGenerator:
  - name: card2-grafana-datasource
    files:
      - datasource.yaml=grafana-datasource.yaml
  - name: card2-grafana-provider
    files:
      - provider.yaml=grafana-dashboard-provider.yaml
  - name: card2-grafana-dashboard
    files:
      - card2-student.json
generatorOptions:
  labels:
    app.kubernetes.io/part-of: card2-observability-kit
