apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: card3-prometheus-data
  labels:
    app.kubernetes.io/name: card3-prometheus
    app.kubernetes.io/part-of: card3-observability-kit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
