apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dw-observability
resources:
  - prometheus.yaml
configMapGenerator:
  - name: card3-prometheus-config
    files:
      - prometheus.yml
generatorOptions:
  labels:
    app.kubernetes.io/part-of: card3-observability-kit
