version: "3.8"
name: "cloudwave_practice3"

services:
  ubuntu:
    image: cloudwave:ubuntu.dig.v1
    container_name: "server"
    build:
      dockerfile: Dockerfile
    command:
      - sleep
      - infinity
  web-app:
    image: nginx:latest
    expose:
      - 80
    deploy:
      replicas: 3