apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: commerce-lab
resources:
  - grafana.yaml
configMapGenerator:
  - name: card1-grafana-datasource
    files:
      - datasource.yaml=grafana-datasource.yaml
  - name: card1-grafana-provider
    files:
      - provider.yaml=grafana-dashboard-provider.yaml
  - name: card1-grafana-dashboard
    files:
      - card1-student.json
generatorOptions:
  labels:
    app.kubernetes.io/part-of: card1-observability-kit
