alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    retention: 2h
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        memory: 128Mi
grafana:
  enabled: true
  adminPassword: admin
  image:
    repository: grafana/grafana
    tag: "13.1.0"
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
prometheus:
  prometheusSpec:
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v3.13.0
    retention: 6h
    scrapeInterval: 10s
    evaluationInterval: 10s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 150m
        memory: 512Mi
      limits:
        memory: 1Gi
defaultRules:
  create: false
kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
